---
general:
  buildTool: "npm"
service:
  buildToolVersion: "N14"
stages:
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "d19c1445trial"
    cfSpace: "dev"
    cfAppName: "btp101010" 
    cfCredentialsId: "auth"

steps:
  # mtaBuild:
  #   buildTarget: 'CF'
  # cloudFoundryDeploy:
  #   apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
  #   org: 'd19c1445trial'
  #   space: 'dev'
  #   credentialsId: 'auth'


