---
general:
  buildTool: "npm"
service:
  buildToolVersion: "N14"
stages:
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "d19c1445trial"
    cfSpace: "dev"
    cfCredentialsId: "auth"

steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
      org: 'd19c1445trial'
      space: 'dev'
      credentialsId: 'auth'

